apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-processing-service-web
  labels:
    app: demo-processing-service-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-processing-service-web
  template:
    metadata:
      labels:
        app: demo-processing-service-web
    spec:
      containers:
        - name: demo-processing-service-web
          image: public.ecr.aws/dissco/demo-processing-service
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: kafka.publisher.host
              value:
            - name: spring.profiles.active
              value: web
            - name: keycloak.auth-server-url
              value:
            - name: keycloak.realm
              value:
            - name: keycloak.resource
              value:
            - name: spring.datasource.url
              value:
            - name: spring.datasource.username
              value:
            - name: spring.datasource.password
              value:
            - name: elasticsearch.hostname
              value:
            - name: elasticsearch.port
              value:
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
