/*
 * This file is generated by jOOQ.
 */
package eu.dissco.demoprocessingservice.database.jooq;


import eu.dissco.demoprocessingservice.database.jooq.tables.DigitalSpecimen;
import eu.dissco.demoprocessingservice.database.jooq.tables.MediaObject;
import eu.dissco.demoprocessingservice.database.jooq.tables.records.DigitalSpecimenRecord;
import eu.dissco.demoprocessingservice.database.jooq.tables.records.MediaObjectRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DigitalSpecimenRecord> DIGITAL_SPECIMEN_PKEY = Internal.createUniqueKey(DigitalSpecimen.DIGITAL_SPECIMEN, DSL.name("digital_specimen_pkey"), new TableField[] { DigitalSpecimen.DIGITAL_SPECIMEN.ID }, true);
    public static final UniqueKey<MediaObjectRecord> MEDIA_OBJECT_PKEY = Internal.createUniqueKey(MediaObject.MEDIA_OBJECT, DSL.name("media_object_pkey"), new TableField[] { MediaObject.MEDIA_OBJECT.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<MediaObjectRecord, DigitalSpecimenRecord> MEDIA_OBJECT__MEDIA_OBJECT_DIGITAL_SPECIMEN_FKEY = Internal.createForeignKey(MediaObject.MEDIA_OBJECT, DSL.name("media_object_digital_specimen_fkey"), new TableField[] { MediaObject.MEDIA_OBJECT.DIGITAL_SPECIMEN }, Keys.DIGITAL_SPECIMEN_PKEY, new TableField[] { DigitalSpecimen.DIGITAL_SPECIMEN.ID }, true);
}
