/*
 * This file is generated by jOOQ.
 */
package eu.dissco.demoprocessingservice.database.jooq;


import eu.dissco.demoprocessingservice.database.jooq.tables.DigitalSpecimen;
import eu.dissco.demoprocessingservice.database.jooq.tables.MediaObject;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.digital_specimen</code>.
     */
    public final DigitalSpecimen DIGITAL_SPECIMEN = DigitalSpecimen.DIGITAL_SPECIMEN;

    /**
     * The table <code>public.media_object</code>.
     */
    public final MediaObject MEDIA_OBJECT = MediaObject.MEDIA_OBJECT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            DigitalSpecimen.DIGITAL_SPECIMEN,
            MediaObject.MEDIA_OBJECT);
    }
}
