/*
 * This file is generated by jOOQ.
 */
package eu.dissco.demoprocessingservice.database.jooq;


import eu.dissco.demoprocessingservice.database.jooq.tables.DigitalSpecimen;
import eu.dissco.demoprocessingservice.database.jooq.tables.MediaObject;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.digital_specimen</code>.
     */
    public static final DigitalSpecimen DIGITAL_SPECIMEN = DigitalSpecimen.DIGITAL_SPECIMEN;

    /**
     * The table <code>public.media_object</code>.
     */
    public static final MediaObject MEDIA_OBJECT = MediaObject.MEDIA_OBJECT;
}
